import type { NextPage } from 'next';
import Head from 'next/head';
import Search from '@components/Search/Search';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Deezer application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Search />
      </main>
    </div>
  );
};

export default Home;
